/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.rubro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GestionCodigo extends javax.swing.JInternalFrame{
    private DefaultTableModel almacencodigo = new DefaultTableModel();

    /**
     * Creates new form GestionCodigo
     */
    public GestionCodigo() {
        initComponents();
        agregarLista();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        escritoriocodigo = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTcodigo = new javax.swing.JTable();
        jBeliminar = new javax.swing.JButton();

        setClosable(true);

        jTcodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTcodigo);

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        escritoriocodigo.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritoriocodigo.setLayer(jBeliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritoriocodigoLayout = new javax.swing.GroupLayout(escritoriocodigo);
        escritoriocodigo.setLayout(escritoriocodigoLayout);
        escritoriocodigoLayout.setHorizontalGroup(
            escritoriocodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(escritoriocodigoLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jBeliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritoriocodigoLayout.setVerticalGroup(
            escritoriocodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritoriocodigoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBeliminar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritoriocodigo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritoriocodigo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
        String jBelimina = "true";
        int filaselecionada = jTcodigo.getSelectedRow();

        if (jBelimina.equalsIgnoreCase("true")) {

            almacencodigo.removeRow(filaselecionada);

        }
        JOptionPane.showMessageDialog(this, "Se ha eliminado la casilla correctamente");


    }//GEN-LAST:event_jBeliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritoriocodigo;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTcodigo;
    // End of variables declaration//GEN-END:variables
    
    
    private void agregarLista(){
    
        almacencodigo.addColumn("Codigo");
        almacencodigo.addColumn("Descripcion");
        almacencodigo.addColumn("Precio");
        almacencodigo.addColumn("Rubro");
        almacencodigo.addColumn("Stock");
        
        jTcodigo.setModel(almacencodigo);
        
    }
    
    
    private void cargarTabla() {
        for (Producto prod : DeTodoSA.listaProductos){
            almacencodigo.addRow(new Object[] {prod.getCodigo(),prod.getDescripcion(),prod.getPrecio(),prod.getRubro(),prod.getStock()});
        }
    }

}
